version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: weather-forecast
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
