version: '3.8'

services:
  api:
    build:
      context: .
    container_name: weather-forecast
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - net
    command: sh -c "npm run build && npm run migration:run && npm run start:prod"

  db:
    image: postgres:latest
    container_name: weather-forecast-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
    ports:
      - 5432:5432
    networks:
      - net

networks:
  net:
    driver: bridge
