version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-forecast
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - net
    command: sh -c "npm run build && npm run migration:run && npm run start:prod"

networks:
  net:
