version: '3.9'

services:
  test-db:
    image: postgres:latest
    container_name: weather-forecast-test-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: weather_forecast_test
    ports:
      - 5436:5432
